// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Vehicle.DataContext
{
    // Record
    public class RecordConfiguration : IEntityTypeConfiguration<Record>
    {
        public void Configure(EntityTypeBuilder<Record> builder)
        {
            builder.ToTable("Record", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_RecordId");

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.VehicleId).HasColumnName(@"VehicleId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Latitude).HasColumnName(@"Latitude").HasColumnType("decimal(8,6)").IsRequired();
            builder.Property(x => x.Longitude).HasColumnName(@"Longitude").HasColumnType("decimal(9,6)").IsRequired();
            builder.Property(x => x.Speed).HasColumnName(@"Speed").HasColumnType("int").IsRequired();
            builder.Property(x => x.Timestamp).HasColumnName(@"Timestamp").HasColumnType("datetime").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Vehicle).WithMany(b => b.Records).HasForeignKey(c => c.VehicleId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Record_Vehicle");
        }
    }

}
// </auto-generated>

