// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Vehicle.DataContext
{
    // Vehicle
    public class Vehicle
    {
        public int Id { get; set; } // Id (Primary key)
        public string Vin { get; set; } // VIN (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child Records where [Record].[VehicleId] point to this entity (FK_Record_Vehicle)
        /// </summary>
        public virtual ICollection<Record> Records { get; set; } // Record.FK_Record_Vehicle

        public Vehicle()
        {
            Records = new List<Record>();
        }
    }

}
// </auto-generated>

